config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  get :games, to: 'games#index'
  namespace :games do
    get :tiny, to: 'tiny#index'
    post :tiny, to: 'tiny#index'

    # webhooks
    post :build_hook, to: 'webhooks#build_hook'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/build.rb
class Build < ApplicationRecord
  validates :platform, presence: true
  validates :game, presence: true
  validates :url, presence: true, uniqueness: true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end

app/models/unity.rb
class Unity

  def initialize
    token = Rails.application.secrets[:unity]["cloud_api_key"]
    @base_url = "https://build-api.cloud.unity3d.com"
    @auth_header = { Authorization: "Token #{token}" }
  end

  def request url
    HTTParty.get("#{@base_url}#{url}", headers: @auth_header, format: :json)
  end

  def download_build url
    response = request(url)
    build_url = response["links"]["download_primary"]["href"]
    HTTParty.get(build_url).body
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/error_handling.rb
module Concerns
  module ErrorHandling
    extend ActiveSupport::Concern

    included do
      # Ideally we would rescue from uncaught errors here, but there appears to
      # be some issues doing so: https://github.com/rails/rails/issues/671

      # rescue_from Exception,                            :with => :page_error
      # rescue_from ActionController::RoutingError,       :with => :rescue_from_routing_error # unless Rails.env.development?
      # rescue_from ActiveRecord::RecordNotFound,         :with => :page_not_found  # unless Rails.env.development?
      # rescue_from AbstractController::ActionNotFound,   :with => :page_not_found
      # rescue_from ActionController::UnknownController,  :with => :page_not_found
    end

  private

    def render_404
      send_file Rails.root.join('public', '404.html'), type: 'text/html; charset=utf-8', disposition: 'inline', status: 404
    end

    def render_403
      send_file Rails.root.join('public', '403.html'), type: 'text/html; charset=utf-8', disposition: 'inline', status: 403
    end

    def rescue_from_routing_error(error)
      case error.message.to_sym
      when :not_found
        page_not_found(error)
      when :forbidden
        page_forbidden(error)
      else
        render :text => error.inspect
      end
    end

    def page_not_found(error)
      Rails.logger.debug "  > Rendering 404 in response to: #{error.inspect}"
      render "shared/errors/not_found", :layout => 'home', :status => :not_found
    end

    def page_forbidden(error)
      Rails.logger.debug "  > Rendering 403 in response to: #{error.inspect}"
      render "shared/errors/forbidden", :layout => 'home', :status => :forbidden
    end

    def page_error(error)
      Rails.logger.debug "  > Rendering 500 in response to: #{error.inspect}"
      render 'shared/errors/server_error', :layout => 'home', :status => 500
    end

  end
end

app/controllers/games/tiny_controller.rb
class Games::TinyController < ApplicationController

  def index
    builds = Build.where(game: 'tiny')

    @x32_builds = builds.where(platform: 'tiny-x32').order('created_at DESC')
    @x64_builds = builds.where(platform: 'tiny-x64').order('created_at DESC')
    @osx_builds = builds.where(platform: 'tiny-osx').order('created_at DESC')

    if request.post?
      email = params[:email]

      if email
        subscriber = Subscriber.create email: email, active: true
        flash[:notice] = "Added to mailing list!"
      end
    end
  end

end

app/controllers/games/webhooks_controller.rb
class Games::WebhooksController < ApplicationController
  protect_from_forgery except: :build_hook

  def build_hook
    links = params[:links]
    project = params[:projectName]
    target_name = params[:buildTargetName]

    if links && project && target_name
      build_url = links[:api_self][:href]

      unity = Unity.new
      file = unity.download_build(build_url)

      key = "builds/#{project}/#{target_name}/#{Time.now.to_i}-#{target_name}.zip"

      resource = Aws::S3::Resource.new
      resource.bucket($s3_bucket).object(key).put(body: file)

      build = Build.find_or_initialize_by url: key
      build.game = project
      build.platform = target_name
      build.save
    else
      render_404
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def aws_url relative
    bucket = Rails.application.secrets[:aws]["bucket"]
    "http://s3.amazonaws.com/#{bucket}/#{relative}"
  end

end

app/views/application/_flash.haml
- if flash.present?
  #flash_alerts

    - %i{notice error info}.each do |kind|
      - if flash[kind].present?
        - css_kind = 'alert-info' if kind.to_s == 'notice'
        - css_kind = 'alert-danger' if kind.to_s == 'error'
        .alert-app.alert{class: css_kind}
          = flash[kind].html_safe
          %button{type: 'button', class: 'close', data: {dismiss: 'alert'}} &times;

  :javascript
    $(function() {
      setTimeout(function() { $(".alert-app").alert('close'); }, 5000);
    });

app/views/application/_header.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      = link_to root_path, class: 'navbar-brand' do
        = image_tag 'logo.png', class: 'pixelated x2'
      = link_to "Willy's Site", root_path, class: 'navbar-brand'

      %button.navbar-toggle.collapsed{'data-toggle': 'collapse', 'data-target': '#nav-menu'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

    .collapse.navbar-collapse#nav-menu
      %ul.nav.navbar-nav#nav-menu
        %li
          =link_to 'Games', games_path

app/views/games/index.haml
.container-fluid
  %h1.text-center Games

  .row
    .col-xs-12.text-center
      %ul.list-unstyled
        %li= link_to 'Tiny Game', games_tiny_path

app/views/games/tiny/index.haml
.container-fluid.text-center
  %h1 Tiny Game
  %p Get notified when there are new builds!

  .col-md-4.col-md-offset-4.gmb
    = form_tag games_tiny_path, method: 'post' do
      .input-group
        = text_field_tag 'email', nil, placeholder: 'email', class: 'form-control'
        %span.input-group-btn
          %input.btn.btn-default{type: 'submit', value: 'Submit'}

  .col-md-6.col-md-offset-3.gmb
    %h2 Latest Builds

    .col-md-4
      %h4 Windows x32
      - if !@x32_builds.empty?
        = link_to 'Download', aws_url(@x32_builds.first.url)

    .col-md-4
      %h4 Windows x64
      - if !@x64_builds.empty?
        = link_to 'Download', aws_url(@x64_builds.first.url)

    .col-md-4
      %h4 OSX
      - if !@osx_builds.empty?
        = link_to 'Download', aws_url(@osx_builds.first.url)

  .col-md-6.col-md-offset-3
    %h2 Previous Builds

    .col-md-4
      %h4 Windows x32
      - @x32_builds.each do |build|
        %p= link_to build.created_at.strftime('%Y-%m-%d'), aws_url(build.url)

    .col-md-4
      %h4 Windows x64
      - @x64_builds.each do |build|
        %p= link_to build.created_at.strftime('%Y-%m-%d'), aws_url(build.url)

    .col-md-4
      %h4 OSX
      - @osx_builds.each do |build|
        %p= link_to build.created_at.strftime('%Y-%m-%d'), aws_url(build.url)

app/views/home/index.haml
#game-area

= javascript_include_tag 'game'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Willy's Website
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    = render 'header'
    = render 'flash'
    = yield
    = render 'footer'